export declare class ProjectBits {
    bits: number;
    constructor(bits: number);
    and: (bit: number) => boolean;
    ironw: () => boolean;
    bauxitew: () => boolean;
    armss: () => boolean;
    egr: () => boolean;
    massirr: () => boolean;
    itc: () => boolean;
    mlp: () => boolean;
    nrf: () => boolean;
    irond: () => boolean;
    vds: () => boolean;
    cia: () => boolean;
    cfce: () => boolean;
    propb: () => boolean;
    uap: () => boolean;
    city_planning: () => boolean;
    adv_city_planning: () => boolean;
    space_program: () => boolean;
    spy_satellite: () => boolean;
    moon_landing: () => boolean;
    pirate_economy: () => boolean;
    recycling_initiative: () => boolean;
    telecom_satellite: () => boolean;
    green_tech: () => boolean;
    arable_land_agency: () => boolean;
    clinical_research_center: () => boolean;
    specialized_police_training: () => boolean;
    adv_engineering_corps: () => boolean;
    gsa_np: () => boolean;
    rnd_np: () => boolean;
    rpc_np: () => boolean;
}
